In [1]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5])
y=np.array(x**2)
z=np.array(x**x)
print(x,y,z)

[1 2 3 4 5] [ 1  4  9 16 25] [   1    4   27  256 3125]


In [4]:
bin(10) ##2진수

'0b1010'

In [10]:
#permutaion
from itertools import permutations
per=permutations([1,2,3,4])
permutations([1,2,3,4], 2)
print(sum(1 for ignore in per))
from itertools import product
from itertools import combinations

24


In [13]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1,0,-1],[1,1,0]])
print(x.shape,y.shape)
print(np.dot(x,y.T))

(2, 3) (2, 3)
[[-2  3]
 [-2  9]]


In [75]:
from numpy import linalg
linalg.det(linalg.inv(np.array([[1,2,2],[2,2,1],[1,2,1]])))

0.5

In [18]:
linalg.qr(np.array([[2,2,0],[-2,1,1],[3,0,1]]))


(array([[-0.48507125, -0.80845208, -0.33333333],
        [ 0.48507125, -0.56591646,  0.66666667],
        [-0.72760688,  0.16169042,  0.66666667]]),
 array([[-4.12310563, -0.48507125, -0.24253563],
        [ 0.        , -2.18282063, -0.40422604],
        [ 0.        ,  0.        ,  1.33333333]]))

In [21]:
np.trace(np.array([[2,2,0],[-2,1,1],[3,0,1]]))

4

In [22]:
linalg.det(np.array([[2,2,0],[-2,1,1],[3,0,1]]))

11.999999999999995

In [23]:
linalg.eig(np.array([[2,2,0],[-2,1,1],[3,0,1]]))

(array([ 0.82780538+2.10555033j,  0.82780538-2.10555033j,  2.34438924+0.j        ]),
 array([[ 0.03855929-0.4714928j ,  0.03855929+0.4714928j ,  0.40793471+0.j        ],
        [ 0.47377641+0.31693492j,  0.47377641-0.31693492j,  0.07024416+0.j        ],
        [-0.67178560+0.j        , -0.67178560-0.j        ,  0.91030491+0.j        ]]))

In [24]:
linalg.solve(np.array([[3,2,1],[1,-1,3],[5,4,-2]]),np.array([7,3,1]))

array([-3.,  6.,  4.])

In [25]:
A = [[i**2, i, 1] for i in range(1930, 2020, 10)]
matA = np.array(A).astype(np.float64)
matA

array([[  3.72490000e+06,   1.93000000e+03,   1.00000000e+00],
       [  3.76360000e+06,   1.94000000e+03,   1.00000000e+00],
       [  3.80250000e+06,   1.95000000e+03,   1.00000000e+00],
       [  3.84160000e+06,   1.96000000e+03,   1.00000000e+00],
       [  3.88090000e+06,   1.97000000e+03,   1.00000000e+00],
       [  3.92040000e+06,   1.98000000e+03,   1.00000000e+00],
       [  3.96010000e+06,   1.99000000e+03,   1.00000000e+00],
       [  4.00000000e+06,   2.00000000e+03,   1.00000000e+00],
       [  4.04010000e+06,   2.01000000e+03,   1.00000000e+00]])

In [26]:
np.linalg.svd(matA, full_matrices = True)

(array([[-0.31976962,  0.51880251,  0.53777077, -0.0168249 ,  0.04075155,
          0.01980856, -0.07965386, -0.25763573, -0.51413703],
        [-0.32309188,  0.39434369,  0.13745023,  0.03592757,  0.18648649,
          0.30616438,  0.39496125,  0.45287709,  0.47991191],
        [-0.32643131,  0.26857409, -0.14891729, -0.45549534, -0.48539484,
         -0.42205349, -0.26547129, -0.01564824,  0.32741567],
        [-0.32978791,  0.14149369, -0.32133176,  0.83421249, -0.1711758 ,
         -0.15580057, -0.11966183, -0.06275957,  0.01490621],
        [-0.33316168,  0.0131025 , -0.3797932 , -0.1909815 ,  0.78707329,
         -0.2078523 , -0.17575827, -0.11664461, -0.03051132],
        [-0.33655261, -0.11659948, -0.32430161, -0.17572412, -0.20910386,
          0.78067897, -0.20637563, -0.17026765, -0.1109971 ],
        [-0.33996072, -0.24761226, -0.15485697, -0.12001535, -0.15970725,
         -0.19020677,  0.78848608, -0.2236287 , -0.22655111],
        [-0.34338599, -0.37993582,  0.1285407 , 

In [28]:
from sympy import * #row echelon

In [29]:
M = Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]])
M.rref()

(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]), (0, 1))

In [33]:
from numpy import array
from scipy.linalg import lu

A = array([[1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
           [1, 1, 0, 0, 1, 0, 1, 0, 1, 1],
           [1, 1, 0, 0, 0, 1, 1, 0, 0, 0],
           [0, 1, 0, 1, 1, 0, 1, 0, 0, 1],
           [1, 1, 0, 0, 1, 1, 1, 1, 1, 1]])

P, L, U = lu(A)

In [36]:
U

array([[ 1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0., -1., -1.,  0.,  0.,  0., -1., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.]])

In [37]:
 M = Matrix([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])
M.nullspace()

[Matrix([
 [-15],
 [  6],
 [  1],
 [  0],
 [  0]]), Matrix([
 [0],
 [0],
 [0],
 [1],
 [0]]), Matrix([
 [   1],
 [-1/2],
 [   0],
 [   0],
 [   1]])]

In [38]:
a=167
b=91
c=0
while a-2>b:
    a=a-2
    c=c+1
print(c)    

37


In [41]:
tan(pi)>sin(pi)

False

In [42]:
sin(1 / 10000) > cos(1 / 10000)

False

In [43]:
3^(3^100000) > 4^(2^100000)

False

In [49]:
import math
math.log((2**1000)(3**100)) < math.log((3**10000)*(2**1000))

TypeError: 'int' object is not callable

In [59]:

a=0
b=2
while b<30 :
    if b in [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]:
        a=a+81
    b=b+1
print(a)
    

810


In [62]:
sum = 0
for n in range(1,101):
    if n%2==1:
        sum = sum + n
    else:
        sum = sum - 2

In [64]:
for x in range(1,2):
    print(x)

1


In [66]:
def f(x):
    result = 1
    for i in range(1,x+1):
        result = result + i 
    return result


In [67]:
f(f(f(3)))

436

In [68]:
f(f(3))

29

In [69]:
f(3)

7

In [73]:
sum=0
for x in range(len([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])-1):
    sum=sum+1/([2, 3, 5, 7, 11, 13, 17, 19, 23, 29][x]*[2, 3, 5, 7, 11, 13, 17, 19, 23, 29][x+1])
print(sum)
    
    

0.2932932238890714


In [74]:
1/(29*31)

0.0011123470522803114